# Generated by Django 2.2.17 on 2021-03-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210222_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='number',
        ),
    ]
