# Generated by Django 2.2.17 on 2021-04-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_expedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredCastings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateField()),
                ('casting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Casting')),
            ],
        ),
        migrations.CreateModel(
            name='MachinedParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Part')),
            ],
        ),
    ]
