# Generated by Django 2.2.17 on 2021-04-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_machinedparts_storedcastings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
